create table CUSTOMER (
CUST_ID varchar(6) Primary key,
CUST_Name varchar(30),
CUST_RegDate Date,
CUST_City varchar(30),
CUST_Contact varchar(20)
);

CREATE TABLE ORDERS (
    ORDER_ID VARCHAR(6) PRIMARY KEY,
    CUST_ID VARCHAR(6),
    EMP_ID VARCHAR(6),
    ORDER_DATE DATE,
    ORDER_TOTAL INT,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

SELECT * FROM ORDERS;

CREATE TABLE ITEM(
    ITEM_ID VARCHAR(6) PRIMARY KEY,
    SUPP_ID VARCHAR(6),
    ITEM_Name VARCHAR(50),
    ITEM_PurchaseUnitPrice INT,
    ITEM_RetailUnitPrice INT,
    ITEM_Qty INT,
    ITEM_BatchID VARCHAR(6),
    ITEM_BatchDate DATE
);

SELECT * FROM ITEM;


CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID INT IDENTITY(1,1) PRIMARY KEY,
    ORDER_ID VARCHAR(6),
    ITEM_ID VARCHAR(6),
    QUANTITY INT,
    UNIT_PRICE INT,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

SELECT * FROM EMPLOYEE;

SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ORDERS';

ALTER TABLE ORDER_DETAILS ADD ORDER_QTY INT;

ALTER TABLE EMPLOYEE  
DROP COLUMN EMP_cit;


ALTER TABLE EMPLOYEE ADD EMP_City varchar(50);


CREATE TABLE EMPLOYEE(
    EMP_ID VARCHAR(6) PRIMARY KEY,
    EMP_Name VARCHAR(30),
    EMP_BirthDay DATE,
    EMP_Cit VARCHAR(30),
    EMP_Login VARCHAR(20),
    EMP_Password VARCHAR(20),
    EMP_Salary INT
);

SELECT * FROM EMPLOYEE;

create table SUPPLIER (
SUPP_ID varchar(6) PRIMARY KEY,
SUPP_Name varchar(50),
SUPP_Address varchar(50),
SUPP_Phone varchar(13),
SUPP_Email varchar(50)
);

SELECT * FROM SUPPLIER 

INSERT INTO SUPPLIER VALUES ('S001','Sohail Plaza','Anarkali Bazar Lahore', '090078601','sohail@gmail.com') 
--Supplier History Table
create table Supplier_History(
SUPP_History_Id int IDENTITY(1,1) PRIMARY KEY,
SUPP_History_Details varchar (1000) NOT NULL
);

CREATE TABLE PURCHASES (
    PURCHASE_ID VARCHAR(6) PRIMARY KEY,
    SUPP_ID VARCHAR(6),
    ITEM_ID VARCHAR(6),
    PURCHASE_DATE DATE,
    QUANTITY INT,
    TOTAL_COST INT,
    FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER(SUPP_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);
ALTER TABLE ITEM ADD STOCK_QTY INT DEFAULT 0;

EXEC sp_help 'PURCHASES';
ALTER TABLE PURCHASES DROP COLUMN PURCHASE_ID;

ALTER TABLE PURCHASES ADD PURCHASE_ID INT IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE PURCHASES DROP CONSTRAINT [PK__PURCHASE__AF7B9D5472D63156];
ALTER TABLE PURCHASES ADD CONSTRAINT PK_PURCHASES PRIMARY KEY (NEW_PURCHASE_ID);

CREATE TABLE SALES (
    SALE_ID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMER_NAME VARCHAR(100),
    SALE_DATE DATETIME DEFAULT GETDATE(),
    TOTAL_AMOUNT DECIMAL(10,2)
);
CREATE TABLE SALES_ITEMS (
    SALE_ITEM_ID INT PRIMARY KEY IDENTITY(1,1),
    SALE_ID INT FOREIGN KEY REFERENCES SALES(SALE_ID),
    ITEM_ID INT FOREIGN KEY REFERENCES ITEM(ITEM_ID),
    QUANTITY INT,
    UNIT_PRICE DECIMAL(10,2),
    TOTAL_PRICE DECIMAL(10,2)
);



